# This file was generated by GoReleaser. DO NOT EDIT.
cask "poddle" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "5cdcb71636f4e32ef00a33fb15660509abbb39351dc757a9ca5c5b9508737c59"
      url "https://github.com/datadir-lab/poddle/releases/download/v#{version}/poddle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "097e44f9030a6ee9a68a44edba1fdac3b472c69f59aeadb3e521865d78f38b5e"
      url "https://github.com/datadir-lab/poddle/releases/download/v#{version}/poddle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "494e79711e0be94e0c71d24571cfd74fa577d8c68e7f7e6c7d4bdde29864dae4"
      url "https://github.com/datadir-lab/poddle/releases/download/v#{version}/poddle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e96a9900b46c0c3b6677881aeabc5eebde651be7d85f1a7de950b1ae54b5cf85"
      url "https://github.com/datadir-lab/poddle/releases/download/v#{version}/poddle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "poddle"
  desc "Self-hostable, secret-safe dev sandboxes for coding agents."
  homepage "https://github.com/datadir-lab/poddle"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "poddle"

  # No zap stanza required

  caveats <<~EOS
    poddle runs pods with podman - install it separately: brew install podman
  EOS
end
