# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Poddle < Formula
  desc "Self-hostable, secret-safe dev sandboxes for coding agents."
  homepage "https://github.com/datadir-lab/poddle"
  version "0.1.1"
  license "AGPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/datadir-lab/poddle/releases/download/v0.1.1/poddle_0.1.1_darwin_amd64.tar.gz"
      sha256 "5cdcb71636f4e32ef00a33fb15660509abbb39351dc757a9ca5c5b9508737c59"
    end
    on_arm do
      url "https://github.com/datadir-lab/poddle/releases/download/v0.1.1/poddle_0.1.1_darwin_arm64.tar.gz"
      sha256 "097e44f9030a6ee9a68a44edba1fdac3b472c69f59aeadb3e521865d78f38b5e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/datadir-lab/poddle/releases/download/v0.1.1/poddle_0.1.1_linux_amd64.tar.gz"
      sha256 "494e79711e0be94e0c71d24571cfd74fa577d8c68e7f7e6c7d4bdde29864dae4"
    end
    on_arm do
      url "https://github.com/datadir-lab/poddle/releases/download/v0.1.1/poddle_0.1.1_linux_arm64.tar.gz"
      sha256 "e96a9900b46c0c3b6677881aeabc5eebde651be7d85f1a7de950b1ae54b5cf85"
    end
  end

  def install
    bin.install "poddle"
  end

  test do
    system "#{bin}/poddle", "version"
  end

  def caveats
    <<~EOS
      poddle runs pods with podman - install it separately: brew install podman
    EOS
  end
end
